services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dog-breed-classifier
    ports:
      - "8501:8501"
    volumes:
      # - ./src:/app/src
      # - ./app.py:/app/app.py

      - ./artefacts:/app/artefacts:ro
      - ./mlruns:/app/mlruns:ro
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_SERVER_HEADLESS=true
      - PYTHONUNBUFFERED=1
      # - MLFLOW_TRACKING_URI=http://mlflow-server:5000

    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mlflow:
    image: python:3.11-slim
    container_name: mlflow-ui
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns:ro
    working_dir: /
    command: >
      sh -c "pip install mlflow && 
             mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:///mlruns"
    restart: unless-stopped
    profiles:
      - mlflow 

networks:
  default:
    name: dog-breed-network